# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tfrecord_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tfrecord_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16tfrecord_service.proto\x12\x08tfrecord\",\n\x13LoadTFRecordRequest\x12\x15\n\rtfrecord_name\x18\x01 \x01(\t\"8\n\x14LoadTFRecordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"?\n\x10GetRecordRequest\x12\x15\n\rtfrecord_name\x18\x01 \x01(\t\x12\x14\n\x0crecord_index\x18\x02 \x01(\x05\"-\n\x11GetRecordResponse\x12\x18\n\x10processed_images\x18\x01 \x03(\x0c\x32\xa6\x01\n\x0fTFRecordService\x12M\n\x0cLoadTFRecord\x12\x1d.tfrecord.LoadTFRecordRequest\x1a\x1e.tfrecord.LoadTFRecordResponse\x12\x44\n\tGetRecord\x12\x1a.tfrecord.GetRecordRequest\x1a\x1b.tfrecord.GetRecordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tfrecord_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADTFRECORDREQUEST']._serialized_start=36
  _globals['_LOADTFRECORDREQUEST']._serialized_end=80
  _globals['_LOADTFRECORDRESPONSE']._serialized_start=82
  _globals['_LOADTFRECORDRESPONSE']._serialized_end=138
  _globals['_GETRECORDREQUEST']._serialized_start=140
  _globals['_GETRECORDREQUEST']._serialized_end=203
  _globals['_GETRECORDRESPONSE']._serialized_start=205
  _globals['_GETRECORDRESPONSE']._serialized_end=250
  _globals['_TFRECORDSERVICE']._serialized_start=253
  _globals['_TFRECORDSERVICE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
