# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upscale.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'upscale.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rupscale.proto\x12\x07upscale\"M\n\x0eUpscaleRequest\x12\x13\n\x0bhas_aligned\x18\x01 \x01(\x08\x12\x16\n\x0eupscale_factor\x18\x02 \x01(\x05\x12\x0e\n\x06images\x18\x03 \x03(\x0c\"+\n\x0fUpscaleResponse\x12\x18\n\x10processed_images\x18\x01 \x03(\x0c\x32T\n\x0eUpscaleService\x12\x42\n\rUpscaleImages\x12\x17.upscale.UpscaleRequest\x1a\x18.upscale.UpscaleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upscale_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPSCALEREQUEST']._serialized_start=26
  _globals['_UPSCALEREQUEST']._serialized_end=103
  _globals['_UPSCALERESPONSE']._serialized_start=105
  _globals['_UPSCALERESPONSE']._serialized_end=148
  _globals['_UPSCALESERVICE']._serialized_start=150
  _globals['_UPSCALESERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
